### ISSUE TITLE
Logout 

### ISSUE THREAD

**Issue by SamiEbadi** [sinanazemi/global-hiring#4]
@AnisaEbadi  Please create the Logout menu in the site header. It should be available on every page in the site which has the header. 
It appears after user click the username or user photo on top right side of the page
Follow the exact size values as much as possible

https://app.zeplin.io/project.html#pid=5774308e5501ecd027f0ed0b&sid=57acd374436a7503161528ae

**Comment by AnisaEbadi** [comment]
The logout for test is ready but the design is not perfect

**Comment by AnisaEbadi** [comment]
I change the design of logout and use the popover bootstrap for that
