### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by SamiEbadi** [sinanazemi/global-hiring#8]
**\* Highest Priority ***

I entered my information in all the steps and saw the filled edit profile page. But then I entered the website from another browser and tried to login to my account  and this was the result: 
<img width="1915" alt="screen shot 2016-08-11 at 2 53 30 pm" src="https://cloud.githubusercontent.com/assets/10181777/17606294/8e48910e-5fd3-11e6-8be1-3c3260a01d84.png">

The expected behavior: 

After a new user passes the first step. It means that he/she is registered to our system as a new user. So right after that the user should be able to login to his/her account from any other session. (for example from another device or browser)

**Comment by levatabasi** [comment]
It works locally. Please check it on server.
